### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by gden138** [weihancug/SSGF-for-HRRS-scene-classification#1]
您好，我是搞遥感图像处理的一名研究生，最近看了咱们的论文：A semi-supervised generative framework with deep learning features for high-resolution remote sensing image scene classification，正好找到了对应的代码，但是作为一个菜鸟，好不容易把caffe环境搭建起来了（cpu下python2.7对应的caffe编译通过），运行代码时候遇到了太多的问题，比如运行selftrain.py出现下面的问题：
File "/home/sys1710/PycharmProjects/guo/SSGF-for-HRRS-scene-classification-master/selftraining.py", line 333, in <module>
    main(sys.argv)
  File "/home/sys1710/PycharmProjects/guo/SSGF-for-HRRS-scene-classification-master/selftraining.py", line 328, in main
    go(num)
  File "/home/sys1710/PycharmProjects/guo/SSGF-for-HRRS-scene-classification-master/selftraining.py", line 264, in go
    svmTrain(num)
  File "/home/sys1710/PycharmProjects/guo/SSGF-for-HRRS-scene-classification-master/selftraining.py", line 193, in svmTrain
    image_dims=(imagesWidth, imagesHeight))
  File "/usr/local/caffe/python/caffe/classifier.py", line 26, in __init__
    caffe.Net.__init__(self, model_file, caffe.TEST, weights=pretrained_file)
RuntimeError: Could not open file deploy_svm_caffenet.prototxt（这里的文件从网上也没找到）

Process finished with exit code 1

对应的模型我已经下载了部分，请问您这部分如何解决？能把您对应的一些参数文件发一下做个参考吗？麻烦您了，谢谢。

**Comment by gden138** [comment]
我的邮箱120828069@qq.com，多多指教，谢谢！

**Comment by weihancug** [comment]
> 我的邮箱120828069@qq.com，多多指教，谢谢！

不好意思刚看到，我把模型文件都传上来，放一个文件夹

**Comment by gden138** [comment]
谢谢🙏




            
            
                
                    
                            
                                
                            
                            
                                120828069
                            
                    
                        
                            
                                    邮箱：120828069@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年03月22日 10:02，Wei Han 写道： 
我的邮箱120828069@qq.com，多多指教，谢谢！

不好意思刚看到，我把模型文件都传上来，放一个文件夹

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/weihancug/SSGF-for-HRRS-scene-classification","title":"weihancug/SSGF-for-HRRS-scene-classification","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/weihancug/SSGF-for-HRRS-scene-classification"}},"updates":{"snippets":[{"icon":"PERSON","message":"@weihancug in #1: \u003e 我的邮箱120828069@qq.com，多多指教，谢谢！\r\n\r\n不好意思刚看到，我把模型文件都传上来，放一个文件夹"}],"action":{"name":"View Issue","url":"https://github.com/weihancug/SSGF-for-HRRS-scene-classification/issues/1#issuecomment-475467927"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/weihancug/SSGF-for-HRRS-scene-classification/issues/1#issuecomment-475467927",
"url": "https://github.com/weihancug/SSGF-for-HRRS-scene-classification/issues/1#issuecomment-475467927",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by weihancug** [comment]
> 谢谢🙏
> 

你好 所有的模型文件都上传了

**Comment by gden138** [comment]
收到了，不明白的再请教您。非常感谢！

**Comment by weihancug** [comment]
> 收到了，不明白的再请教您。非常感谢！

 不用客气
